"""initial schema

Revision ID: 1f41269b23cb
Revises: 
Create Date: 2026-09-07 04:41:51.175970
"""
from alembic import op
import sqlalchemy as sa
import app.db.types


revision = '1f41269b23cb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_models',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider_id', sa.String(length=64), nullable=False),
    sa.Column('model_id', sa.String(length=128), nullable=False),
    sa.Column('display_name', sa.String(length=128), nullable=False),
    sa.Column('supports_streaming', sa.Boolean(), nullable=False),
    sa.Column('supports_tools', sa.Boolean(), nullable=False),
    sa.Column('supports_structured_output', sa.Boolean(), nullable=False),
    sa.Column('supports_reasoning', sa.Boolean(), nullable=False),
    sa.Column('supports_embeddings', sa.Boolean(), nullable=False),
    sa.Column('supports_vision', sa.Boolean(), nullable=False),
    sa.Column('context_window', sa.Integer(), nullable=True),
    sa.Column('pricing_info', sa.String(length=256), nullable=True),
    sa.Column('availability_status', sa.String(length=32), nullable=False),
    sa.Column('is_embedding', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider_id', 'model_id', name='uq_provider_model')
    )
    op.create_index(op.f('ix_ai_models_provider_id'), 'ai_models', ['provider_id'], unique=False)
    op.create_table('ai_providers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider_id', sa.String(length=64), nullable=False),
    sa.Column('provider_name', sa.String(length=128), nullable=False),
    sa.Column('adapter', sa.String(length=64), nullable=False),
    sa.Column('base_url', sa.String(length=1024), nullable=True),
    sa.Column('api_key_encrypted', sa.Text(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('availability_status', sa.String(length=32), nullable=False),
    sa.Column('default_model', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_providers_provider_id'), 'ai_providers', ['provider_id'], unique=True)
    op.create_table('ai_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('question', sa.Text(), nullable=True),
    sa.Column('provider_id', sa.String(length=64), nullable=True),
    sa.Column('model_id', sa.String(length=128), nullable=True),
    sa.Column('reasoning', sa.String(length=32), nullable=True),
    sa.Column('retrieval_mode', sa.String(length=32), nullable=True),
    sa.Column('archive_only', sa.Boolean(), nullable=False),
    sa.Column('answer', sa.Text(), nullable=True),
    sa.Column('confidence', sa.String(length=32), nullable=True),
    sa.Column('documents_retrieved', sa.Integer(), nullable=False),
    sa.Column('chunks_retrieved', sa.Integer(), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('app_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=128), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('is_secret', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_app_settings_key'), 'app_settings', ['key'], unique=True)
    op.create_table('archive_collections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('collection_key', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=512), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_archive_collections_collection_key'), 'archive_collections', ['collection_key'], unique=True)
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('label', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_categories_key'), 'categories', ['key'], unique=True)
    op.create_table('crawl_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_key', sa.String(length=64), nullable=False),
    sa.Column('status', sa.Enum('pending', 'running', 'succeeded', 'failed', 'skipped', 'not_applicable', name='processingstatus'), nullable=False),
    sa.Column('seed_urls', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('stats', sa.Text(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crawl_runs_source_key'), 'crawl_runs', ['source_key'], unique=False)
    op.create_table('entities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=512), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('coord_precision', sa.String(length=32), nullable=True),
    sa.Column('coord_source', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entity_type', 'name', name='uq_entity')
    )
    op.create_index(op.f('ix_entities_entity_type'), 'entities', ['entity_type'], unique=False)
    op.create_index(op.f('ix_entities_name'), 'entities', ['name'], unique=False)
    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_key', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('event_date', sa.String(length=32), nullable=True),
    sa.Column('date_precision', sa.Enum('exact', 'month', 'year', 'decade', 'unknown', name='dateprecision'), nullable=False),
    sa.Column('source', sa.Enum('verified', 'deterministic', 'ai', 'unknown', name='metadatasource'), nullable=False),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_events_event_key'), 'events', ['event_key'], unique=True)
    op.create_table('research_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=True),
    sa.Column('question', sa.Text(), nullable=True),
    sa.Column('answer', sa.Text(), nullable=True),
    sa.Column('citations_json', sa.Text(), nullable=True),
    sa.Column('sources_json', sa.Text(), nullable=True),
    sa.Column('provider_id', sa.String(length=64), nullable=True),
    sa.Column('model_id', sa.String(length=128), nullable=True),
    sa.Column('retrieval_mode', sa.String(length=32), nullable=True),
    sa.Column('confidence', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('saved_searches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('query', sa.Text(), nullable=False),
    sa.Column('filters', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_key', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=512), nullable=False),
    sa.Column('base_url', sa.String(length=1024), nullable=True),
    sa.Column('doc_prefix', sa.String(length=16), nullable=False),
    sa.Column('next_seq', sa.Integer(), nullable=False),
    sa.Column('rights_status', sa.String(length=128), nullable=True),
    sa.Column('access_status', sa.String(length=128), nullable=True),
    sa.Column('copyright_notes', sa.Text(), nullable=True),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sources_source_key'), 'sources', ['source_key'], unique=True)
    op.create_table('topics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('label', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_topics_key'), 'topics', ['key'], unique=True)
    op.create_table('documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=1024), nullable=True),
    sa.Column('subtitle', sa.String(length=1024), nullable=True),
    sa.Column('author', sa.String(length=512), nullable=True),
    sa.Column('authors', sa.Text(), nullable=True),
    sa.Column('doc_date', sa.String(length=32), nullable=True),
    sa.Column('date_precision', sa.Enum('exact', 'month', 'year', 'decade', 'unknown', name='dateprecision'), nullable=False),
    sa.Column('publisher', sa.String(length=512), nullable=True),
    sa.Column('document_type', sa.String(length=128), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('language', sa.String(length=32), nullable=True),
    sa.Column('page_count', sa.Integer(), nullable=True),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('collection_id', sa.Integer(), nullable=True),
    sa.Column('source_url', sa.String(length=2048), nullable=True),
    sa.Column('archived_url', sa.String(length=2048), nullable=True),
    sa.Column('archive_provider', sa.String(length=128), nullable=True),
    sa.Column('archive_snapshot_timestamp', sa.String(length=32), nullable=True),
    sa.Column('local_path', sa.String(length=2048), nullable=True),
    sa.Column('mime_type', sa.String(length=128), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('sha256', sa.String(length=64), nullable=True),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rights_status', sa.String(length=128), nullable=True),
    sa.Column('access_status', sa.String(length=128), nullable=True),
    sa.Column('copyright_notes', sa.Text(), nullable=True),
    sa.Column('metadata_only', sa.Boolean(), nullable=False),
    sa.Column('download_status', sa.Enum('pending', 'running', 'succeeded', 'failed', 'skipped', 'not_applicable', name='processingstatus'), nullable=False),
    sa.Column('text_extraction_status', sa.Enum('pending', 'running', 'succeeded', 'failed', 'skipped', 'not_applicable', name='processingstatus'), nullable=False),
    sa.Column('ocr_status', sa.Enum('pending', 'running', 'succeeded', 'failed', 'skipped', 'not_applicable', name='processingstatus'), nullable=False),
    sa.Column('metadata_status', sa.Enum('pending', 'running', 'succeeded', 'failed', 'skipped', 'not_applicable', name='processingstatus'), nullable=False),
    sa.Column('index_status', sa.Enum('pending', 'running', 'succeeded', 'failed', 'skipped', 'not_applicable', name='processingstatus'), nullable=False),
    sa.Column('embedding_status', sa.Enum('pending', 'running', 'succeeded', 'failed', 'skipped', 'not_applicable', name='processingstatus'), nullable=False),
    sa.Column('metadata_source', sa.Enum('verified', 'deterministic', 'ai', 'unknown', name='metadatasource'), nullable=False),
    sa.Column('review_status', sa.Enum('unreviewed', 'verified', 'needs_review', 'incorrect_metadata', 'duplicate', 'ocr_poor', 'source_uncertain', name='reviewstatus'), nullable=False),
    sa.Column('duplicate_of_id', sa.Integer(), nullable=True),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['collection_id'], ['archive_collections.id'], ),
    sa.ForeignKeyConstraint(['duplicate_of_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id', name='uq_documents_document_id')
    )
    op.create_index(op.f('ix_documents_document_id'), 'documents', ['document_id'], unique=False)
    op.create_index(op.f('ix_documents_is_demo'), 'documents', ['is_demo'], unique=False)
    op.create_index(op.f('ix_documents_sha256'), 'documents', ['sha256'], unique=False)
    op.create_table('citations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ai_run_id', sa.Integer(), nullable=True),
    sa.Column('citation_ref', sa.String(length=32), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=True),
    sa.Column('chunk_id', sa.String(length=64), nullable=True),
    sa.Column('page_number', sa.Integer(), nullable=True),
    sa.Column('quote', sa.Text(), nullable=True),
    sa.Column('validated', sa.Boolean(), nullable=False),
    sa.Column('validation_note', sa.String(length=512), nullable=True),
    sa.ForeignKeyConstraint(['ai_run_id'], ['ai_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_citations_ai_run_id'), 'citations', ['ai_run_id'], unique=False)
    op.create_table('crawl_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=2048), nullable=False),
    sa.Column('normalized_url', sa.String(length=2048), nullable=True),
    sa.Column('http_status', sa.Integer(), nullable=True),
    sa.Column('content_type', sa.String(length=256), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('outcome', sa.String(length=32), nullable=False),
    sa.Column('reason', sa.String(length=512), nullable=True),
    sa.Column('document_id', sa.Integer(), nullable=True),
    sa.Column('discovered_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['crawl_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crawl_items_normalized_url'), 'crawl_items', ['normalized_url'], unique=False)
    op.create_index(op.f('ix_crawl_items_run_id'), 'crawl_items', ['run_id'], unique=False)
    op.create_table('document_chunks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chunk_id', sa.String(length=64), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=True),
    sa.Column('section', sa.String(length=512), nullable=True),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('char_start', sa.Integer(), nullable=True),
    sa.Column('char_end', sa.Integer(), nullable=True),
    sa.Column('token_estimate', sa.Integer(), nullable=True),
    sa.Column('embedding', app.db.types.Vector(), nullable=True),
    sa.Column('embedding_model', sa.String(length=128), nullable=True),
    sa.Column('embedding_dims', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_chunks_chunk_id'), 'document_chunks', ['chunk_id'], unique=True)
    op.create_index(op.f('ix_document_chunks_document_id'), 'document_chunks', ['document_id'], unique=False)
    op.create_table('document_entities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=True),
    sa.Column('mention', sa.String(length=512), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('source', sa.Enum('verified', 'deterministic', 'ai', 'unknown', name='metadatasource'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_entities_document_id'), 'document_entities', ['document_id'], unique=False)
    op.create_index(op.f('ix_document_entities_entity_id'), 'document_entities', ['entity_id'], unique=False)
    op.create_table('document_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_events_document_id'), 'document_events', ['document_id'], unique=False)
    op.create_index(op.f('ix_document_events_event_id'), 'document_events', ['event_id'], unique=False)
    op.create_table('document_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('local_path', sa.String(length=2048), nullable=False),
    sa.Column('mime_type', sa.String(length=128), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('sha256', sa.String(length=64), nullable=True),
    sa.Column('checksum_algo', sa.String(length=16), nullable=False),
    sa.Column('checksum_computed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_files_document_id'), 'document_files', ['document_id'], unique=False)
    op.create_table('document_pages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('char_count', sa.Integer(), nullable=False),
    sa.Column('text_source', sa.String(length=32), nullable=True),
    sa.Column('ocr_confidence', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id', 'page_number', name='uq_page')
    )
    op.create_index(op.f('ix_document_pages_document_id'), 'document_pages', ['document_id'], unique=False)
    op.create_table('document_topics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('evidence', sa.Text(), nullable=True),
    sa.Column('source', sa.Enum('verified', 'deterministic', 'ai', 'unknown', name='metadatasource'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id', 'topic_id', name='uq_doc_topic')
    )
    op.create_index(op.f('ix_document_topics_document_id'), 'document_topics', ['document_id'], unique=False)
    op.create_index(op.f('ix_document_topics_topic_id'), 'document_topics', ['topic_id'], unique=False)
    op.create_table('document_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('version_no', sa.Integer(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=True),
    sa.Column('local_path', sa.String(length=2048), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_versions_document_id'), 'document_versions', ['document_id'], unique=False)
    op.create_table('ocr_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('engine', sa.String(length=64), nullable=True),
    sa.Column('engine_version', sa.String(length=64), nullable=True),
    sa.Column('status', sa.Enum('pending', 'running', 'succeeded', 'failed', 'skipped', 'not_applicable', name='processingstatus'), nullable=False),
    sa.Column('pages_processed', sa.Integer(), nullable=False),
    sa.Column('mean_confidence', sa.Float(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ocr_runs_document_id'), 'ocr_runs', ['document_id'], unique=False)
    op.create_table('processing_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_type', sa.String(length=64), nullable=False),
    sa.Column('status', sa.Enum('pending', 'running', 'succeeded', 'failed', 'skipped', 'not_applicable', name='processingstatus'), nullable=False),
    sa.Column('payload', sa.Text(), nullable=True),
    sa.Column('result', sa.Text(), nullable=True),
    sa.Column('error_type', sa.String(length=128), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('document_id', sa.Integer(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('progress', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_processing_jobs_job_type'), 'processing_jobs', ['job_type'], unique=False)
    op.create_table('research_notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.Column('document_id', sa.Integer(), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['session_id'], ['research_sessions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('research_notes')
    op.drop_index(op.f('ix_processing_jobs_job_type'), table_name='processing_jobs')
    op.drop_table('processing_jobs')
    op.drop_index(op.f('ix_ocr_runs_document_id'), table_name='ocr_runs')
    op.drop_table('ocr_runs')
    op.drop_index(op.f('ix_document_versions_document_id'), table_name='document_versions')
    op.drop_table('document_versions')
    op.drop_index(op.f('ix_document_topics_topic_id'), table_name='document_topics')
    op.drop_index(op.f('ix_document_topics_document_id'), table_name='document_topics')
    op.drop_table('document_topics')
    op.drop_index(op.f('ix_document_pages_document_id'), table_name='document_pages')
    op.drop_table('document_pages')
    op.drop_index(op.f('ix_document_files_document_id'), table_name='document_files')
    op.drop_table('document_files')
    op.drop_index(op.f('ix_document_events_event_id'), table_name='document_events')
    op.drop_index(op.f('ix_document_events_document_id'), table_name='document_events')
    op.drop_table('document_events')
    op.drop_index(op.f('ix_document_entities_entity_id'), table_name='document_entities')
    op.drop_index(op.f('ix_document_entities_document_id'), table_name='document_entities')
    op.drop_table('document_entities')
    op.drop_index(op.f('ix_document_chunks_document_id'), table_name='document_chunks')
    op.drop_index(op.f('ix_document_chunks_chunk_id'), table_name='document_chunks')
    op.drop_table('document_chunks')
    op.drop_index(op.f('ix_crawl_items_run_id'), table_name='crawl_items')
    op.drop_index(op.f('ix_crawl_items_normalized_url'), table_name='crawl_items')
    op.drop_table('crawl_items')
    op.drop_index(op.f('ix_citations_ai_run_id'), table_name='citations')
    op.drop_table('citations')
    op.drop_index(op.f('ix_documents_sha256'), table_name='documents')
    op.drop_index(op.f('ix_documents_is_demo'), table_name='documents')
    op.drop_index(op.f('ix_documents_document_id'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_topics_key'), table_name='topics')
    op.drop_table('topics')
    op.drop_index(op.f('ix_sources_source_key'), table_name='sources')
    op.drop_table('sources')
    op.drop_table('saved_searches')
    op.drop_table('research_sessions')
    op.drop_index(op.f('ix_events_event_key'), table_name='events')
    op.drop_table('events')
    op.drop_index(op.f('ix_entities_name'), table_name='entities')
    op.drop_index(op.f('ix_entities_entity_type'), table_name='entities')
    op.drop_table('entities')
    op.drop_index(op.f('ix_crawl_runs_source_key'), table_name='crawl_runs')
    op.drop_table('crawl_runs')
    op.drop_index(op.f('ix_categories_key'), table_name='categories')
    op.drop_table('categories')
    op.drop_index(op.f('ix_archive_collections_collection_key'), table_name='archive_collections')
    op.drop_table('archive_collections')
    op.drop_index(op.f('ix_app_settings_key'), table_name='app_settings')
    op.drop_table('app_settings')
    op.drop_table('ai_runs')
    op.drop_index(op.f('ix_ai_providers_provider_id'), table_name='ai_providers')
    op.drop_table('ai_providers')
    op.drop_index(op.f('ix_ai_models_provider_id'), table_name='ai_models')
    op.drop_table('ai_models')
    # ### end Alembic commands ###
